name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build the website
      run: npx parcel build src/index.html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pages: write

    needs: build
    
    environment:
      name: github-pages
      
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
